# Generated by Django 4.2.7 on 2024-02-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_userstories', '0002_user_last_login_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='recipient_email',
            new_name='recipient_id',
        ),
        migrations.RenameField(
            model_name='emails',
            old_name='sender_email',
            new_name='sender_id',
        ),
    ]
