# Generated by Django 4.2.7 on 2024-02-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_userstories', '0003_rename_recipient_email_emails_recipient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='emails',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
