# Generated by Django 4.2.7 on 2024-02-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_userstories', '0004_rename_recipient_id_emails_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
